### ISSUE TITLE
Jar for Android?

### ISSUE THREAD

**Issue by venil7** [rubenlagus/TelegramBotsExample#10]
is ot possible to compile this into JAR and use in android project?

**Comment by rubenlagus** [comment]
Have you try running maven with options `clean compile assembly:single` ?

That should provide a jar, but I've never tested in Android projects. Please if you do, give me feedback ;)

**Comment by rubenlagus** [comment]
@venil7 A bit late, but extracted everything related to the api to an external project, you may just fetch it using gradly and try it out in android (can't say if it will work): https://jitpack.io/#rubenlagus/TelegramBots/v1.0

**Comment by venil7** [comment]
@rubenlagus :+1:
