### ISSUE TITLE
Jar file without Maven or Eclipse

### ISSUE THREAD

**Issue by sportsdinero** [rubenlagus/TelegramBotsExample#11]
I simply develop off of notepad and was wondering if you can supply a jar file for this project.
Thanks

**Comment by pavel-kurnosov** [comment]
This will help you: 
https://jitpack.io/#rubenlagus/TelegramBots/0.1Beta
Support maven, gradle, stb

**Comment by rubenlagus** [comment]
Great solution @pavel-kurnosov 

Thanks

**Comment by rubenlagus** [comment]
Following @pavel-kurnosov idea, it is now available in jitpack, but as a separete project. Please use carefully as there were tons of changes: https://jitpack.io/#rubenlagus/TelegramBots/v1.0
