### ISSUE TITLE
group chat

### ISSUE THREAD

**Issue by FabianTerhorst** [rubenlagus/TelegramBotsExample#2]
i don´t know if its a bug or i have missed something but i don´t get a callback when a group message is written without say it directly to the bot with @ Botname.

**Comment by rubenlagus** [comment]
It is not a bug, it is something related with the privacy configuration of your bot.

If you have it enabled, your bot will receive:
1. Messages in private chats
2. Messages in group chats that mention your bot with @ Botname
3. Messages in group that are answer to your bot

You can change your bot privacy status using @ BotFather

Hope that helps
