### ISSUE TITLE
PreparedStatement need to be closed

### ISSUE THREAD

**Issue by kalyaganov** [rubenlagus/TelegramBotsExample#32]
I'm a little bit confused. Don't you need to close PreparedStatement every time you use it?

In Java documentation it says that user need to close statements after he use it. 
http://docs.oracle.com/javase/tutorial/jdbc/basics/prepared.html

**Comment by rubenlagus** [comment]
They should be closed on their own, but you are right, the correct way should be closing them just after they are not needed.
