### ISSUE TITLE
ReplyKeyboardHide.class is missing

### ISSUE THREAD

**Issue by nnasirzada** [rubenlagus/TelegramBotsExample#33]
I couldn't find ReplyKeyboardHide.class in source code. Is there something wrong with [this library](https://github.com/rubenlagus/TelegramBots) ?

Eclipse highlights [this import statement](https://github.com/rubenlagus/TelegramBotsExample/blob/master/src/main/java/org/telegram/updateshandlers/DirectionsHandlers.java#L13-L13) and says **"The import org.telegram.telegrambots.api.objects.replykeyboard.ReplyKeyboardHide; cannot be resolved"**.

An object of the same class is used [here](https://github.com/rubenlagus/TelegramBotsExample/blob/master/src/main/java/org/telegram/updateshandlers/DirectionsHandlers.java#L112-L114) too.

**Comment by rubenlagus** [comment]
That class was removed in later versions, but Master branch should work as it is (no extra changes needed). Just make sure you haven't change the library version.

In any case, you can use dev branch if you want to check with last version of TelegramBots library.

**Comment by nnasirzada** [comment]
So, how can I add this class to my project?
