### ISSUE TITLE
org.telegram.database.ConectionDB.checkVersion null pointer exception

### ISSUE THREAD

**Issue by yazeed44** [rubenlagus/TelegramBotsExample#6]
Exception in thread "main" java.lang.NullPointerException
    at org.telegram.database.ConectionDB.checkVersion(ConectionDB.java:72)
    at org.telegram.database.DatabaseManager.<init>(DatabaseManager.java:38)
    at org.telegram.database.DatabaseManager.getInstance(DatabaseManager.java:55)
    at org.telegram.updatesreceivers.UpdatesThread.<init>(UpdatesThread.java:50)
    at net.yazeed44.cdpnebot.CdpneIntroBot.<init>(CdpneIntroBot.java:28)
    at net.yazeed44.cdpnebot.Main.main(Main.java:9)

**Comment by yazeed44** [comment]
``` java
public CdpneIntroBot(){

        SenderHelper.SendWebhook("", TOKEN);
        new UpdatesThread(TOKEN, this);

        setup();
    }
```

**Comment by rubenlagus** [comment]
It seems that your database connection is not correct.
1. Has you installed mysql correctly in your server?
2. Check that `BuildVars.linkDB`, `BuildVars.userDB` and `BuildVars.passwordDB` have correct values your database and user

**Comment by yazeed44** [comment]
But i don't want to use database

**Comment by rubenlagus** [comment]
In that case, remove database folder and all the references to those classes. That simple.

**Comment by yazeed44** [comment]
That doesn't seem like a clean solution for me , why not add an option for that ?

**Comment by rubenlagus** [comment]
Because all the bots I'm building need a database, so it makes no sense that I add that option at all.

In addition, a bot that doesn't, at least, store the **last update received** makes not sense.
If you don't save that value, you may run in duplicated answers to user upon restart or when deploying a new version.
Even when using a webhook it is a nice idea check that the received update is not an older update that was send twice (for any strange reason).

**Comment by yazeed44** [comment]
Right now i'm using sqlite , maybe i should move to mysql

Thanks anyway

**Comment by simk0024** [comment]
I have latest mySQL server installed in my system,
userDB = "root";
databaseName = "tele01";
linkDB = "jdbc:mysql://localhost:3306/" + databaseName + "?useUnicode=true&characterEncoding=UTF-8";
The "tele01" is created and in used, but I am still getting the same error.
