### ISSUE TITLE
Making requests when getting updates

### ISSUE THREAD

**Issue by 9px** [rubenlagus/TelegramBotsExample#9]
hi. telegram [recently](https://core.telegram.org/bots/api#making-requests-when-getting-updates) add an ability to perform a request to the telegram Bot API while sending an answer to the webhook.
can you do a simple implement of this feature in your bot?

**Comment by rubenlagus** [comment]
Hi, I will add this feature asap.  Currently I'm quite busy to implement new features. 

Sorry for the delay, feel free to make a pull request if you have a working implementation

**Comment by rubenlagus** [comment]
Closed via 392dc6f5f02b9a8d4f69b3aa573e495ec9e0d649

Added requests when getting updates via webhook only for those method that are completely supported with json format
